### ISSUE TITLE
NoClassDefFoundError in SecretManager client after update to 7.4.4

### ISSUE THREAD

**Issue by ccudennec-otto** [GoogleCloudPlatform/spring-cloud-gcp#4312]
**Describe the bug**
I get the following error when starting my application:

```
Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
	at com.google.cloud.secretmanager.v1.ListSecretsRequest.<clinit>(ListSecretsRequest.java:41)
	at com.google.cloud.secretmanager.v1.stub.GrpcSecretManagerServiceStub.<clinit>(GrpcSecretManagerServiceStub.java:72)
	at com.google.cloud.secretmanager.v1.stub.SecretManagerServiceStubSettings.createStub(SecretManagerServiceStubSettings.java:359)
	at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.<init>(SecretManagerServiceClient.java:455)
	at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.create(SecretManagerServiceClient.java:437)
	at com.google.cloud.spring.autoconfigure.secretmanager.GcpSecretManagerAutoConfiguration.secretManagerClient(GcpSecretManagerAutoConfiguration.java:75)
```

The Spring Boot application is not able to startup.
* Spring Boot 3.5.6
* Spring Cloud GCP 7.4.3
* Java 21 Temurin

I tried to follow the release notes but were not able to spot something suspicious. 

Thanks,

Christopher

**Comment by blakeli0** [comment]
Hi @ccudennec-otto, the release notes have been updated with more information. This is due to libraries-bom [v26.75.0](https://github.com/googleapis/java-cloud-bom/releases/tag/v26.75.0) upgraded protobuf to 4.33.2.  

On the other hand, the protobuf-java verision comes from spring-cloud-gcp should be 4.33.2 already. Are you downgrading protobuf-java to 3.x in your application? If yes, removing the explicit version declaration in your project, you should be good to go.

**Comment by ccudennec-otto** [comment]
Yes, indeed we managed the Protobuf version manually to solve some CVE case in the past. I removed the custom managed version and now the services comes up! Thanks for your quick response! 🌻
